name: lovesusie
version: 1
handle:
- mime: if( path ~ "\..html$") type "text/html"
- directoryindex: index.html Love-master/index.html 1/Love-master/index.html
- compress: if ( out_header["Content-type"] ~ "text/css" ) compress
- compress: if ( out_header["Content-type"] ~ "text/javascript" ) compress
- compress: if ( out_header["Content-type"] ~ "text/html" ) compress
- compress: if ( out_header["Content-type"] ~ "image/jpeg" ) compress
- passwdaccess:  passwd "susie:qmy-6487"
